---
- name: learning to recall var data
  hosts: localhost
  connection: local

  vars:
          telecom:
                  - ericsson
                  - alu
                  - avaya
                  - cisco
          heroes:
                  marvel:
                          - spiderman
                          - ironman
                          - daredevil
                  dc:
                          - wonderwoman
                          - batman
                          - superman
  tasks:
          - name: print out spiderman
            debug:
                    msg: "{{ heroes.marvel[0] }}"
            tags:
                    - wip

          - name: print out batman
            debug:
                    msg: "{{ heroes.dc[1] }}"
            tags:
                    - wip

          - name: print out ALL dc heroes
            debug:
                    msg: "{{ item }}"
            loop: "{{ heroes.dc }}"
            tags:
                    - wip

          - name: print out cisco
            debug:
                    msg: "{{ telecom[3] }}"
            tags:
                    - wip

          - name: print out ALL dc AND marvel heroes
            debug:
                    msg: "{{ heroes }}"
            tags:
                    - wip

